version: '1'
services:
  postgres:
    image: 'postgres'
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres'
#  springapp:
#    image: 'springboot'
#    container_name: 'spring_app'
#    ports:
#      - 8880:8080
#    depends_on:
#      - postgres